### ISSUE TITLE
No sending/receiving data on serial_driver_bridge

### ISSUE THREAD

**Issue by afonsofonbraga** [ros-drivers/transport_drivers#63]
Hi, 
 I wasn't able to neither send nor receive anything with launching the  serial_driver_bridge_node.launch.py
 I'm trying to execute the launch file using the configurations of my device:
``` 
/**:
  ros__parameters:
    device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
```
I'm using ros2 galactic in docker. I'm sending the following  message to my device :
```
echo -ne '\x00\x00\x45\x44\x76\x00\x00\x36\xFF\x4F' > /dev/ttyUSB0
```
 and I'm receiving back a message (using hexdump):
 ```
 0000000    0000    0000    0076    3600    4eff    0000    0000    0000
0000010    0000    0000    0000    0000    0000    0000    0000    0000
*
0000060    0000    0000    0000    0000    0000    0000    0000    b578
 ```
 Is there any other special config to make it work?
Thanks
